# Generated by Django 4.2.1 on 2023-06-28 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(verbose_name='Цена авто')),
                ('photo', models.ImageField(blank=True, default=None, null=True, upload_to='cars/images/', verbose_name='Фото авто')),
                ('year_of_manufacture', models.CharField(max_length=10, verbose_name='Год выпуска')),
                ('description', models.TextField(blank=True, verbose_name='Описание авто')),
                ('mileage', models.PositiveIntegerField(verbose_name='Пробег')),
                ('transmission_type', models.CharField(choices=[('AUTOMATIC', 'automatic'), ('MANUAL', 'manual'), ('CVT', 'cvt')], max_length=50, verbose_name='Тип коробки передач')),
                ('drive_type', models.CharField(choices=[('FRONT_DRIVE', 'front-wheel drive'), ('REAR_DRIVE', 'rear drive'), ('FOUR_WHEEL', 'four-wheel drive')], default='front-wheel drive', max_length=50, verbose_name='Тип привода')),
                ('engine_capacity', models.FloatField(verbose_name='Объем двигателя')),
                ('engine_type', models.CharField(choices=[('PETROL', 'petrol engine'), ('DIESEL', 'diesel engine')], default='petrol engine', max_length=50, verbose_name='Тип двигателя')),
                ('car_power', models.SmallIntegerField(verbose_name='Мощность автомобиля л.с.')),
                ('number_of_owners', models.SmallIntegerField(verbose_name='Количество владельцев')),
                ('_is_active', models.BooleanField(default=False, verbose_name='Объявление размещено')),
                ('_is_closed', models.BooleanField(default=False, verbose_name='Объявление снято с публикации')),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100, verbose_name='Название модели')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_name', models.CharField(max_length=100, verbose_name='Название опции')),
            ],
        ),
        migrations.CreateModel(
            name='CarOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_option', to='cars.car')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_option', to='cars.option')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='car_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car_model', to='cars.carmodel', verbose_name='Модель авто'),
        ),
        migrations.AddField(
            model_name='car',
            name='options',
            field=models.ManyToManyField(through='cars.CarOption', to='cars.option', verbose_name='Дополнительные опции'),
        ),
        migrations.AddField(
            model_name='car',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Car', to=settings.AUTH_USER_MODEL),
        ),
    ]
